/**
 * Tekrarlayan Gelir Otomatik Oluşturma Servisi
 */

import type { Income } from "@/types";
import {
  shouldGenerateRecurringIncome,
  createRecurringIncomeInstance,
  calculateNextIncomeDate,
} from "@/utils/recurring-income-helpers";

/**
 * Tekrarlayan gelirleri kontrol edip yeni instance'lar oluşturur
 * @param incomes Mevcut gelirler listesi
 * @returns Yeni oluşturulan gelirler ve güncellenmiş orijinal gelirler
 */
export function processRecurringIncomes(incomes: Income[]): {
  newIncomes: Income[];
  updatedIncomes: Income[];
} {
  const newIncomes: Income[] = [];
  const updatedIncomes: Income[] = [];

  // Tekrarlayan gelirleri filtrele (otomatik oluşturulmuş olanları hariç tut)
  const recurringIncomes = incomes.filter(
    (income) =>
      income.recurrence &&
      income.recurrence.frequency !== "none" &&
      !income.autoGenerated
  );

  for (const income of recurringIncomes) {
    // Oluşturulması gerekip gerekmediğini kontrol et
    if (shouldGenerateRecurringIncome(income)) {
      // Yeni gelir instance'ı oluştur
      const newIncome = createRecurringIncomeInstance(
        income,
        income.recurrence!.nextDate!
      );
      newIncomes.push(newIncome);

      // Orijinal geliri güncelle (nextDate ve repeatCount)
      const updatedIncome: Income = {
        ...income,
        recurrence: {
          ...income.recurrence!,
          nextDate: calculateNextIncomeDate(
            income.recurrence!.nextDate!,
            income.recurrence!.frequency
          ),
          repeatCount:
            income.recurrence!.repeatCount !== undefined
              ? income.recurrence!.repeatCount - 1
              : undefined,
        },
        updatedAt: new Date().toISOString(),
      };

      // Tekrar sayısı 0'a ulaştıysa tekrarlamayı durdur
      if (
        updatedIncome.recurrence!.repeatCount !== undefined &&
        updatedIncome.recurrence!.repeatCount <= 0
      ) {
        updatedIncome.recurrence!.frequency = "none" as any;
      }

      updatedIncomes.push(updatedIncome);
    }
  }

  return { newIncomes, updatedIncomes };
}

/**
 * Tekrarlayan gelirleri kontrol edip uygulama state'ini günceller
 * Bu fonksiyon uygulama başlangıcında veya periyodik olarak çağrılmalı
 */
export async function checkAndGenerateRecurringIncomes(
  incomes: Income[],
  addIncome: (income: Partial<Income>) => Promise<void>,
  updateIncome: (id: string, updates: Partial<Income>) => Promise<void>
): Promise<void> {
  const { newIncomes, updatedIncomes } = processRecurringIncomes(incomes);

  // Yeni gelirleri ekle
  for (const newIncome of newIncomes) {
    await addIncome(newIncome);
  }

  // Orijinal gelirleri güncelle
  for (const updatedIncome of updatedIncomes) {
    await updateIncome(updatedIncome.id, {
      recurrence: updatedIncome.recurrence,
      updatedAt: updatedIncome.updatedAt,
    });
  }

  console.log(
    `✅ ${newIncomes.length} yeni tekrarlayan gelir oluşturuldu, ${updatedIncomes.length} gelir güncellendi`
  );
}
