/**
 * Ödeme Ekleme Ekranı
 */

import { ScrollView, Text, View, TouchableOpacity, Alert } from "react-native";
import { useState } from "react";
import { useRouter } from "expo-router";
import { ScreenContainer } from "@/components/screen-container";
import { TextInputField, DatePickerField, PickerField, SwitchField } from "@/components/form-input";
import { calculatePeriodCount, calculateTotalAmount } from "@/utils/date-helpers";
import { generateInstallments, generateRecurringPayments } from "@/utils/installment-helpers";
import { useApp } from "@/lib/app-context";
import {
  PaymentCategory,
  PaymentStatus,
  RecurrenceFrequency,
  RECURRENCE_NAMES,
} from "@/types";
import { useTranslation } from "react-i18next";
import { formatCurrency } from "@/utils/currency-helpers";

export default function AddPaymentScreen() {
  const router = useRouter();
  const { t, i18n } = useTranslation();
  const { addPayment } = useApp();

  const [name, setName] = useState("");
  const [amount, setAmount] = useState("");
  const [category, setCategory] = useState<PaymentCategory>(PaymentCategory.OTHER);
  const [dueDate, setDueDate] = useState(new Date());
  const [notes, setNotes] = useState("");
  const [hasInstallments, setHasInstallments] = useState(false);
  const [installmentTotal, setInstallmentTotal] = useState("");
  const [installmentCurrent, setInstallmentCurrent] = useState("");
  const [installmentEndDate, setInstallmentEndDate] = useState<Date | null>(null);
  const [autoGenerateInstallments, setAutoGenerateInstallments] = useState(false);
  const [recurrenceEndDate, setRecurrenceEndDate] = useState<Date | null>(null);
  const [autoGenerateRecurrence, setAutoGenerateRecurrence] = useState(false);
  const [hasRecurrence, setHasRecurrence] = useState(false);
  const [recurrenceFrequency, setRecurrenceFrequency] = useState<RecurrenceFrequency>(RecurrenceFrequency.MONTHLY);
  const [errors, setErrors] = useState<Record<string, string>>({});

  const categoryOptions = [
    { label: t("categories.creditCard"), value: PaymentCategory.CREDIT_CARD },
    { label: t("categories.loan"), value: PaymentCategory.LOAN },
    { label: t("categories.other"), value: PaymentCategory.OTHER },
  ];

  const recurrenceOptions = [
    { label: t("recurrence.daily"), value: RecurrenceFrequency.DAILY },
    { label: t("recurrence.weekly"), value: RecurrenceFrequency.WEEKLY },
    { label: t("recurrence.monthly"), value: RecurrenceFrequency.MONTHLY },
    { label: t("recurrence.yearly"), value: RecurrenceFrequency.YEARLY },
  ];

  const validate = (): boolean => {
    const newErrors: Record<string, string> = {};
    if (!name.trim()) newErrors.name = t("paymentDetail.nameRequired");
    if (!amount.trim()) newErrors.amount = t("paymentDetail.amountRequired");
    else if (isNaN(Number(amount)) || Number(amount) <= 0) newErrors.amount = t("paymentDetail.validAmount");
    if (hasInstallments) {
      if (!installmentTotal.trim()) newErrors.installmentTotal = t("paymentDetail.validNumber");
      else if (isNaN(Number(installmentTotal)) || Number(installmentTotal) <= 0) newErrors.installmentTotal = t("paymentDetail.validNumber");
      // Otomatik oluşturma aktif değilse mevcut taksit gerekli
      if (!autoGenerateInstallments) {
        if (!installmentCurrent.trim()) newErrors.installmentCurrent = t("paymentDetail.validNumber");
        else if (isNaN(Number(installmentCurrent)) || Number(installmentCurrent) <= 0) newErrors.installmentCurrent = t("paymentDetail.validNumber");
      }
    }
    setErrors(newErrors);
    return Object.keys(newErrors).length === 0;
  };

  const handleSubmit = async () => {
    if (!validate()) return;

    // Otomatik tekrarlanan ödeme oluşturma aktifse
    if (hasRecurrence && autoGenerateRecurrence && recurrenceEndDate) {
      const recurringPayments = generateRecurringPayments(
        name.trim(),
        Number(amount),
        category,
        dueDate,
        recurrenceEndDate,
        recurrenceFrequency,
        notes.trim() || undefined
      );

      // Tüm tekrarlanan ödemeleri ekle
      for (const payment of recurringPayments) {
        await addPayment({ ...payment, autoGenerated: true });
      }

      Alert.alert(
        t("paymentDetail.success"),
        t("paymentDetail.recurringCreated", { count: recurringPayments.length }),
        [{ text: t("paymentDetail.ok"), onPress: () => router.back() }]
      );
      return;
    }

    // Otomatik taksit oluşturma aktifse
    if (hasInstallments && autoGenerateInstallments) {
      const installments = generateInstallments(
        name.trim(),
        Number(amount),
        category,
        dueDate,
        Number(installmentTotal),
        notes.trim() || undefined
      );

      // Tüm taksitleri ekle
      for (const installment of installments) {
        await addPayment({ ...installment, autoGenerated: true });
      }

      Alert.alert(
        t("paymentDetail.success"),
        t("paymentDetail.installmentsCreated", { count: installments.length }),
        [{ text: t("paymentDetail.ok"), onPress: () => router.back() }]
      );
      return;
    }

    // Normal ödeme ekleme
    const payment = {
      name: name.trim(),
      amount: Number(amount),
      category,
      dueDate: dueDate.toISOString(),
      status: PaymentStatus.PENDING,
      isPaid: false,
      notes: notes.trim() || undefined,
      installments: hasInstallments ? { 
        total: Number(installmentTotal), 
        current: Number(installmentCurrent),
        endDate: installmentEndDate ? installmentEndDate.toISOString() : undefined
      } : undefined,
      recurrence: hasRecurrence ? { 
        frequency: recurrenceFrequency,
        endDate: recurrenceEndDate ? recurrenceEndDate.toISOString() : undefined
      } : undefined,
    };
    await addPayment(payment);
    Alert.alert(t("paymentDetail.success"), t("paymentDetail.addTitle"), [{ text: t("paymentDetail.ok"), onPress: () => router.back() }]);
  };

  return (
    <ScreenContainer>
      <ScrollView className="flex-1" contentContainerStyle={{ paddingHorizontal: 16, paddingTop: 16, paddingBottom: 32 }}>
        {/* Geri Dönme Butonu */}
        <TouchableOpacity
          onPress={() => router.back()}
          className="flex-row items-center mb-4"
        >
          <Text className="text-2xl text-primary mr-2">‹</Text>
          <Text className="text-base text-primary font-medium">{t("common.back")}</Text>
        </TouchableOpacity>

        <View className="mb-6">
          <Text className="text-3xl font-bold text-foreground">{t("paymentDetail.addTitle")}</Text>
          <Text className="text-base text-muted mt-1">{t("paymentDetail.subtitle")}</Text>
        </View>
        <TextInputField label={t("paymentDetail.name")} value={name} onChangeText={setName} placeholder={t("paymentDetail.name")} error={errors.name} required />
        <TextInputField label={t("paymentDetail.amount")} value={amount} onChangeText={setAmount} placeholder="0.00" keyboardType="numeric" error={errors.amount} required />
        <PickerField label={t("paymentDetail.category")} value={category} onChange={(value) => setCategory(value as PaymentCategory)} options={categoryOptions} required />
        <DatePickerField label={t("paymentDetail.paymentDate")} value={dueDate} onChange={setDueDate} required />
        <TextInputField label={t("paymentDetail.notes")} value={notes} onChangeText={setNotes} placeholder={t("paymentDetail.notes")} multiline />
        <SwitchField label={t("paymentDetail.installmentPayment")} value={hasInstallments} onChange={setHasInstallments} />
        {hasInstallments && (
          <View className="ml-4 mb-4">
            <SwitchField 
              label="Otomatik Oluştur" 
              value={autoGenerateInstallments} 
              onChange={(value) => {
                setAutoGenerateInstallments(value);
                if (value) {
                  setInstallmentCurrent("1"); // Otomatik oluşturma aktifse ilk taksit 1
                }
              }} 
              description="Tüm taksitleri otomatik oluştur" 
            />
            <TextInputField label={t("paymentDetail.totalInstallments")} value={installmentTotal} onChangeText={setInstallmentTotal} placeholder="12" keyboardType="numeric" error={errors.installmentTotal} required />
            {!autoGenerateInstallments && (
              <TextInputField label={t("paymentDetail.currentInstallment")} value={installmentCurrent} onChangeText={setInstallmentCurrent} placeholder="3" keyboardType="numeric" error={errors.installmentCurrent} required />
            )}
            <DatePickerField label={t("paymentDetail.lastInstallmentDate")} value={installmentEndDate || new Date()} onChange={setInstallmentEndDate} />
            {autoGenerateInstallments && installmentTotal && (
              <View className="mt-2 p-3 bg-surface rounded-lg border border-border">
                <Text className="text-xs text-muted mb-1">⚠️ Otomatik Oluşturma</Text>
                <Text className="text-sm text-foreground">
                  {installmentTotal} adet taksit otomatik oluşturulacak (aylık)
                </Text>
              </View>
            )}
          </View>
        )}
        <SwitchField label={t("paymentDetail.recurringPayment")} value={hasRecurrence} onChange={setHasRecurrence} />
        {hasRecurrence && (
          <View className="ml-4 mb-4">
            <SwitchField 
              label="Otomatik Oluştur" 
              value={autoGenerateRecurrence} 
              onChange={setAutoGenerateRecurrence} 
              description="Tüm tekrarlanan ödemeleri otomatik oluştur" 
            />
            <PickerField label={t("paymentDetail.frequency")} value={recurrenceFrequency} onChange={(value) => setRecurrenceFrequency(value as RecurrenceFrequency)} options={recurrenceOptions} required />
            <DatePickerField label={t("paymentDetail.lastPaymentDate")} value={recurrenceEndDate || new Date()} onChange={setRecurrenceEndDate} />
            {recurrenceEndDate && amount && (
              <View className="mt-2 p-3 bg-surface rounded-lg border border-border">
                <Text className="text-xs text-muted mb-1">{t("paymentDetail.totalAmountCalculation")}</Text>
                <Text className="text-sm text-foreground">
                  {calculatePeriodCount(dueDate, recurrenceEndDate, recurrenceFrequency)} dönem × {formatCurrency(Number(amount))} = {' '}
                  <Text className="font-semibold text-primary">
                    {formatCurrency(calculateTotalAmount(Number(amount), dueDate, recurrenceEndDate, recurrenceFrequency))}
                  </Text>
                </Text>
              </View>
            )}
            {autoGenerateRecurrence && recurrenceEndDate && (
              <View className="mt-2 p-3 bg-surface rounded-lg border border-border">
                <Text className="text-xs text-muted mb-1">⚠️ Otomatik Oluşturma</Text>
                <Text className="text-sm text-foreground">
                  {calculatePeriodCount(dueDate, recurrenceEndDate, recurrenceFrequency)} adet ödeme otomatik oluşturulacak ({RECURRENCE_NAMES[recurrenceFrequency].toLowerCase()})
                </Text>
              </View>
            )}
          </View>
        )}
        <View className="flex-row gap-3 mt-6">
          <TouchableOpacity className="flex-1 bg-surface border border-border rounded-2xl p-4 items-center active:opacity-80" onPress={() => router.back()}>
            <Text className="text-foreground font-semibold text-base">{t("paymentDetail.cancel")}</Text>
          </TouchableOpacity>
          <TouchableOpacity className="flex-1 bg-primary rounded-2xl p-4 items-center active:opacity-80" onPress={handleSubmit}>
              <Text className="text-background font-semibold text-base">{t("common.add")}</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>
    </ScreenContainer>
  );
}
