/**
 * Tekrarlayan Gelir Yardımcı Fonksiyonları
 */

import type { Income, RecurrenceFrequency } from "@/types";

/**
 * Bir sonraki gelir tarihini hesaplar
 */
export function calculateNextIncomeDate(
  currentDate: string,
  frequency: RecurrenceFrequency
): string {
  const date = new Date(currentDate);

  switch (frequency) {
    case "daily":
      date.setDate(date.getDate() + 1);
      break;
    case "weekly":
      date.setDate(date.getDate() + 7);
      break;
    case "monthly":
      date.setMonth(date.getMonth() + 1);
      break;
    case "yearly":
      date.setFullYear(date.getFullYear() + 1);
      break;
    default:
      return currentDate;
  }

  return date.toISOString().split("T")[0];
}

/**
 * Tekrarlayan gelirin yeni bir instance'ını oluşturur
 */
export function createRecurringIncomeInstance(
  originalIncome: Income,
  newDate: string
): Income {
  const newIncome: Income = {
    ...originalIncome,
    id: `${originalIncome.id}_${Date.now()}`,
    date: newDate,
    autoGenerated: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  // Bir sonraki tarihi hesapla
  if (newIncome.recurrence) {
    newIncome.recurrence.nextDate = calculateNextIncomeDate(
      newDate,
      newIncome.recurrence.frequency
    );

    // Tekrar sayısını azalt
    if (newIncome.recurrence.repeatCount !== undefined) {
      newIncome.recurrence.repeatCount -= 1;
    }
  }

  return newIncome;
}

/**
 * Tekrarlayan gelirin oluşturulması gerekip gerekmediğini kontrol eder
 */
export function shouldGenerateRecurringIncome(income: Income): boolean {
  // Tekrarlama bilgisi yoksa false
  if (!income.recurrence || income.recurrence.frequency === "none") {
    return false;
  }

  // Bir sonraki tarih yoksa false
  if (!income.recurrence.nextDate) {
    return false;
  }

  // Tekrar sayısı 0 ise false
  if (income.recurrence.repeatCount !== undefined && income.recurrence.repeatCount <= 0) {
    return false;
  }

  // Bitiş tarihi geçmişse false
  if (income.recurrence.endDate) {
    const endDate = new Date(income.recurrence.endDate);
    const today = new Date();
    if (endDate < today) {
      return false;
    }
  }

  // Bir sonraki tarih bugün veya geçmişse true
  const nextDate = new Date(income.recurrence.nextDate);
  const today = new Date();
  today.setHours(0, 0, 0, 0);

  return nextDate <= today;
}

/**
 * Tekrarlayan gelirleri filtreler
 */
export function getRecurringIncomes(incomes: Income[]): Income[] {
  return incomes.filter(
    (income) =>
      income.recurrence &&
      income.recurrence.frequency !== "none" &&
      !income.autoGenerated // Sadece orijinal gelirleri al
  );
}

/**
 * Otomatik oluşturulan gelirleri filtreler
 */
export function getAutoGeneratedIncomes(incomes: Income[]): Income[] {
  return incomes.filter((income) => income.autoGenerated === true);
}
